import { getTranslations } from "next-intl/server";
import { CodeBlock, DemoBox, DemoPage, Section } from "@/components/demo-page";

export default async function OgApiPage() {
	const t = await getTranslations("api.og");

	return (
		<DemoPage title={t("title")} description={t("description")}>
			<Section title={t("preview")} description={t("previewDesc")}>
				<DemoBox>
					<div className="overflow-hidden rounded-lg border">
						{/* biome-ignore lint/performance/noImgElement: OG image is dynamically generated by API route, not a static asset */}
						{/* biome-ignore lint/a11y/noRedundantAlt: alt describes the generated content */}
						<img
							src="/api/og?title=Hello"
							alt="OG Preview"
							className="w-full"
						/>
					</div>
				</DemoBox>
			</Section>

			<Section title={t("howItWorks")}>
				<CodeBlock
					filename="lib/api/routes/og.ts"
					language="typescript"
				>{`import { Hono } from "hono";
import { ImageResponse } from "next/og";

export const ogRoute = new Hono();

ogRoute.get("/", (c) => {
  const title = c.req.query("title") || "Next.js Learning Hub";
  const description =
    c.req.query("description") || "Interactive feature showcase";

  return new ImageResponse(
    (
      <div
        style={{
          height: "100%",
          width: "100%",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          backgroundColor: "#09090b",
          color: "#fafafa",
          fontFamily: "sans-serif",
        }}
      >
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            gap: "16px",
          }}
        >
          <div style={{ fontSize: 64, fontWeight: 700 }}>{title}</div>
          <div style={{ fontSize: 28, color: "#a1a1aa" }}>{description}</div>
        </div>
      </div>
    ),
    {
      width: 1200,
      height: 630,
    }
  ) as unknown as Response;
});`}</CodeBlock>
			</Section>

			<Section title={t("queryParams")} description={t("queryParamsDesc")}>
				<CodeBlock filename="URL Examples" language="bash">{`# Default
/api/og

# Custom title
/api/og?title=My+Custom+Title

# Title + description
/api/og?title=Hello&description=World`}</CodeBlock>
			</Section>

			<Section title={t("keyPoints")}>
				<div className="grid gap-3 sm:grid-cols-2">
					<DemoBox title={t("jsxToImage")}>
						<p className="text-sm text-muted-foreground">
							{t("jsxToImageDesc")}
						</p>
					</DemoBox>
					<DemoBox title={t("dynamicContent")}>
						<p className="text-sm text-muted-foreground">
							{t("dynamicContentDesc")}
						</p>
					</DemoBox>
				</div>
			</Section>
		</DemoPage>
	);
}
